### ISSUE TITLE
do you want fourthdowncalculator.com?

### ISSUE THREAD

**Issue by kevinburke** [TheUpshot/4thdownbot-model#9]
Hi,
A few years ago I bought fourthdowncalculator.com and put a website up there, because Brian Burke's website wasn't mobile friendly. My efforts were very soon outshadowed by your model and the resources of the NYT.

Do you want the domain? Happy to do what I can to support NFL numeracy!

**Comment by kevinburke** [comment]
Bumping this before the season starts - let me know!

**Comment by treycausey** [comment]
No thanks, @kevinburke but I think we'll pass! Appreciate the offer.
